### ISSUE TITLE
handlers folder

### ISSUE THREAD

**Issue by lightsuner** [BarstoolSports/serverless-micro#2]
Hi, could anybody help me? I got an error:

> (node:58736) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: [copy base] file does not exist > "/Users/ls/lambdabackendnewts/handlers/public.js": ENOENT: no such file or directory, open '/Users/ls/lambdabackendnewts/handlers/public.js'

My config is: (I don't have any **handlers** folder in my project)

```
functions:
  helloDashboard:
    service: public
    handler: "services/public/endpoints/test/hello/handler.handler"
    name: ${self:provider.stage}-helloDashboard
    events:
      - http: get test/hello
```
Thanks.
